version: '3'
services:
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
    ports:
     - "7868:7865"
    volumes:
     - ~/repositories:/app/repositories
     - ~/.cache/pip:/root/.cache/pip
     - .:/app

