version: '3'
services:
  web:
    build: .
    ports:
     - "7865:7865"
    command: python3 main.py --host 0.0.0.0 --sync-repo='skip' --queue-size=88
    volumes:
     - ~/repositories:/app/repositories
     - ~/.cache/pip:/root/.cache/pip
    environment:
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
