version: '3'
services:
  api-1:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7868:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  api-2:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7865:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  api-3:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7869:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  api-4:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7870:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
