version: '3.8'

x-common-env: &common-env
  TZ: Asia/Shanghai
  PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
  NVIDIA_DRIVER_CAPABILITIES: compute,utility

services:
  web-1: &web-1
    image: socus-api:latest
    environment:
      <<: *common-env
      NVIDIA_VISIBLE_DEVICES: 0
    ports:
     - "7868:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped

  web-2:
    <<: *web-1
    environment:
      <<: *common-env
      NVIDIA_VISIBLE_DEVICES: 1
    ports:
     - "7869:7865"
    restart: unless-stopped

  web-3:
    <<: *web-1
    environment:
      <<: *common-env
      NVIDIA_VISIBLE_DEVICES: 2
    ports:
     - "7870:7865"
    restart: unless-stopped

  web-4:
    <<: *web-1
    environment:
      <<: *common-env
      NVIDIA_VISIBLE_DEVICES: 3
    ports:
     - "7871:7865"
    restart: unless-stopped

volumes:
  pip-cache:
    external: true
