version: '3'
services:
  web-1:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7868:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  web-2:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=2
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7865:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  web-3:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=3
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7869:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  web-4:
    image: socus-api:latest
    environment:
      - TZ=Asia/Shanghai
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=4
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
     - "7870:7865"
    volumes:
      - ~/.cache/pip:/root/.cache/pip
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
