version: '3'
services:
  web:
    build: .
    ports:
     - "7865:7865"
    volumes:
     - ~/repositories:/app/repositories
     - ~/.cache/pip:/root/.cache/pip
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
