version: '3'
services:
  web:
    build: .
    ports:
     - "7865:7865"
    volume:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
