version: '3'
services:
  web:
    build: .
    ports:
     - "7878:7878"
    volumes:
     - ~/repositories:/app/repositories
     - ~/.cache/pip:/root/.cache/pip
    environment:
      PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['3']
              capabilities: [gpu]
